title: "TruCol"
url: https://trucol.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch

repo: https://github.com/trucol/trucol
comments: false

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll/imgix

collections:
  tools:
    output: true
    permalink: /tools/:title/
  team-members:
    order:
      - victoria.md
      - eric.md
      - akke.md
      - marc.md
      - subhechha.md
      - chihab.md

defaults:
  - scope:
      type: tools
    values:
      layout: tool

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Author settings
author:
  name     : "TruCol"

# social settings
og_locale: "en_US"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt", "Rakefile", "netlify.toml"]

imgix:
  source: mdg.imgix.net 